/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareCompleteRouteImport } from './routes/share/complete'
import { Route as SShareIdRouteImport } from './routes/s/$shareId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareCompleteRoute = ShareCompleteRouteImport.update({
  id: '/share/complete',
  path: '/share/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareIdRoute = SShareIdRouteImport.update({
  id: '/s/$shareId',
  path: '/s/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/s/$shareId': typeof SShareIdRoute
  '/share/complete': typeof ShareCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/s/$shareId': typeof SShareIdRoute
  '/share/complete': typeof ShareCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/s/$shareId': typeof SShareIdRoute
  '/share/complete': typeof ShareCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/login' | '/s/$shareId' | '/share/complete'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login' | '/s/$shareId' | '/share/complete'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/s/$shareId'
    | '/share/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SShareIdRoute: typeof SShareIdRoute
  ShareCompleteRoute: typeof ShareCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/complete': {
      id: '/share/complete'
      path: '/share/complete'
      fullPath: '/share/complete'
      preLoaderRoute: typeof ShareCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareId': {
      id: '/s/$shareId'
      path: '/s/$shareId'
      fullPath: '/s/$shareId'
      preLoaderRoute: typeof SShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SShareIdRoute: SShareIdRoute,
  ShareCompleteRoute: ShareCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
